/*
 * crypto_xof/try.c version 20240530
 * D. J. Bernstein
 * Public domain.
 * Auto-generated by trygen.py; do not edit.
 */

#include "crypto_xof.h"
#include "try.h"

const char *primitiveimplementation = crypto_xof_IMPLEMENTATION;

#define TUNE_BYTES 1536
#ifdef SMALL
#define MAXTEST_BYTES 128
#else
#define MAXTEST_BYTES 16384
#endif
#ifdef TIMECOP
#define LOOPS TIMECOP_LOOPS
#else
#ifdef SMALL
#define LOOPS 64
#else
#define LOOPS 512
#endif
#endif

#include "test-loops.inc"

static unsigned char *h;
static unsigned char *m;
static unsigned char *h2;
static unsigned char *m2;
unsigned long long hlen;
unsigned long long mlen;

void preallocate(void)
{
}

void allocate(void)
{
  unsigned long long alloclen = 0;
  if (alloclen < TUNE_BYTES) alloclen = TUNE_BYTES;
  if (alloclen < MAXTEST_BYTES) alloclen = MAXTEST_BYTES;
  h = alignedcalloc(alloclen);
  m = alignedcalloc(alloclen);
  h2 = alignedcalloc(alloclen);
  m2 = alignedcalloc(alloclen);
}

void unalign(void)
{
  ++h;
  ++m;
  ++h2;
  ++m2;
}

void realign(void)
{
  --h;
  --m;
  --h2;
  --m2;
}

void predoit(void)
{
}

void doit(void)
{
  crypto_xof(h,TUNE_BYTES,m,TUNE_BYTES);
}

void test(void)
{
  unsigned long long loop;
  
  for (loop = 0;loop < LOOPS;++loop) {
    mlen = myrandom() % (MAXTEST_BYTES + 1);
    hlen = myrandom() % (MAXTEST_BYTES + 1);
    
    output_prepare(h2,h,hlen);
    input_prepare(m2,m,mlen);
    poison(m,mlen);
    crypto_xof(h,hlen,m,mlen);
    unpoison(h,hlen);
    unpoison(m,mlen);
    checksum(h,hlen);
    output_compare(h2,h,hlen,"crypto_xof");
    input_compare(m2,m,mlen,"crypto_xof");
    
    double_canary(h2,h,hlen);
    double_canary(m2,m,mlen);
    poison(m2,mlen);
    crypto_xof(h2,hlen,m2,mlen);
    unpoison(h2,hlen);
    unpoison(m2,mlen);
    if (memcmp(h2,h,hlen) != 0) fail("crypto_xof is nondeterministic");
    
#if crypto_xof_NOOVERLAP == 1
#else
    double_canary(h2,h,hlen);
    double_canary(m2,m,mlen);
    poison(m2,mlen);
    crypto_xof(m2,hlen,m2,mlen);
    unpoison(m2,hlen);
    if (memcmp(m2,h,hlen) != 0) fail("crypto_xof does not handle m=h overlap");
    memcpy(m2,m,mlen);
#endif
  }
#include "test-more.inc"
}
