#include "parameters.h"
#define CRYPTO_BYTES crypto_BYTES
#define CRYPTO_PUBLICKEYBYTES PUBLICKEY_BYTES
#define CRYPTO_SECRETKEYBYTES (KEM_SECRETKEY_BYTES+PUBLICKEY_BYTES)
#define CRYPTO_CIPHERTEXTBYTES CIPHERTEXT_BYTES
