#!/bin/sh

echo "=== `date` === hostname"
$SSHDEVICE hostname || :

echo "=== `date` === uname -a"
$SSHDEVICE uname -a || :
echo "=== `date` === uname -M"
$SSHDEVICE uname -M || :
echo "=== `date` === uname -F"
$SSHDEVICE uname -F || :

echo "=== `date` === /usr/sbin/lscfg | grep proc"
$SSHDEVICE /usr/sbin/lscfg | grep proc || :
echo "=== `date` === /usr/sbin/lsattr -El proc0"
$SSHDEVICE /usr/sbin/lsattr -El proc0 || :
echo "=== `date` === cat /proc/cpuinfo"
$SSHDEVICE cat /proc/cpuinfo || :
echo "=== `date` === lscpu"
$SSHDEVICE lscpu || :

echo "=== `date` === grep . /dev/null /sys/devices/intel_pt/max_nonturbo_ratio"
$SSHDEVICE grep . /dev/null /sys/devices/intel_pt/max_nonturbo_ratio || :

$SSHDEVICE find /sys/devices/system/cpu |
egrep '/topology/physical_package_id$|/topology/core_id$|/topology/thread_siblings_list$|/online$|/cpufreq/cpuinfo_..._freq$|/cpufreq/scaling_governor$|/cpufreq/scaling_setspeed$|/cpufreq/scaling_cur_freq$|/cpufreq/cpb$|/intel_pstate/no_turbo$|/clock_tick$|/regs/identification$' |
while read fn
do
  echo "=== `date` === grep . /dev/null $fn"
  $SSHDEVICE grep . /dev/null $fn
done

echo "=== `date` === sysctl hw.model"
$SSHDEVICE sysctl hw.model || :
echo "=== `date` === sysctl machdep.tsc_freq"
$SSHDEVICE sysctl machdep.tsc_freq || :
echo "=== `date` === /usr/sbin/psrinfo -v"
$SSHDEVICE /usr/sbin/psrinfo -v || :

echo "=== `date` === gcc --version"
gcc --version || :
echo "=== `date` === g++ --version"
g++ --version || :
echo "=== `date` === clang --version"
clang --version || :
echo "=== `date` === clang++ --version"
clang++ --version || :
echo "=== `date` === rustc --version"
rustc --version || :
echo "=== `date` === cargo --version"
cargo --version || :

echo "=== `date` === valgrind --version"
valgrind --version || :
echo "=== `date` === valgrind --help-dyn-options"
valgrind --help-dyn-options || :

# MacOS
echo "=== `date` === sw_vers"
$SSHDEVICE sw_vers || :
echo "=== `date` === system_profiler -detailLevel mini"
$SSHDEVICE system_profiler -detailLevel mini || :
echo "=== `date` === sysctl -n machdep.cpu.brand_string"
$SSHDEVICE sysctl -n machdep.cpu.brand_string || :
