#ifndef __PARAMETERS_H__
#define __PARAMETERS_H__

#define MQOM2_PARAM_SECURITY 256
#define MQOM2_PARAM_BASE_FIELD 8
#define MQOM2_PARAM_TRADEOFF 0
#define MQOM2_PARAM_NBROUNDS 3

#define FIELDS_REF

#define NO_MISALIGNED_ACCESSES
#define MEMORY_EFFICIENT_PIOP
#define MEMORY_EFFICIENT_BLC
#define MEMORY_EFFICIENT_KEYGEN
#define USE_XOF_X4
#define USE_ENC_X8

#define MQOM2_FOR_SUPERCOP

#endif /* __PARAMETERS_H__ */
