#!/bin/sh -e

okabi | (
  while read abi
  do
    for bits in 8 16 32 64
    do
      for sign in int uint
      do
        target="$sign""$bits"
        okc-$abi | (
          while read c
          do
            [ -f include/$abi/crypto_$target.h ] && continue

            echo "=== `date` === $abi testing crypto_$target under $c..." >&2
            rm -f crypto_$target test-$target.c test-$target.o ${target}_optblocker.o
            sed -e s/TYPE/crypto_$target/g -e s/N/$bits/g < test-$sign.c > test-$target.c
            $c -c ${target}_optblocker.c || continue
            $c -o crypto_$target test-$target.c ${target}_optblocker.o || continue
            ./crypto_$target 1 0 || continue

            echo "=== `date` === $abi passed crypto_$target under $c" >&2
            mkdir -p lib/$abi
            cp ${target}_optblocker.o lib/$abi/
            mkdir -p include/$abi
            cp crypto_$target.h include/$abi/crypto_$target.h
          done
        )
      done
    done
  done
)
