
#pragma once

#define CROSS_keygen                                    CRYPTO_NAMESPACE(CROSS_keygen)
#define CROSS_sign                                      CRYPTO_NAMESPACE(CROSS_sign)
#define CROSS_verify                                    CRYPTO_NAMESPACE(CROSS_verify)
#define expand_digest_to_fixed_weight                   CRYPTO_NAMESPACE(expand_digest_to_fixed_weight)
#define gen_seed_tree                                   CRYPTO_NAMESPACE(gen_seed_tree)
#define pack_fp_syn                                     CRYPTO_NAMESPACE(pack_fp_syn)
#define pack_fp_vec                                     CRYPTO_NAMESPACE(pack_fp_vec)
#define pack_fz_rsdp_g_vec                              CRYPTO_NAMESPACE(pack_fz_rsdp_g_vec)
#define pack_fz_vec                                     CRYPTO_NAMESPACE(pack_fz_vec)
#define rebuild_leaves                                  CRYPTO_NAMESPACE(rebuild_leaves)
#define rebuild_tree                                    CRYPTO_NAMESPACE(rebuild_tree)
#define recompute_root                                  CRYPTO_NAMESPACE(recompute_root)
#define seed_leaves                                     CRYPTO_NAMESPACE(seed_leaves)
#define seed_path                                       CRYPTO_NAMESPACE(seed_path)
#define tree_proof                                      CRYPTO_NAMESPACE(tree_proof)
#define tree_root                                       CRYPTO_NAMESPACE(tree_root)
#define unpack_fp_syn                                   CRYPTO_NAMESPACE(unpack_fp_syn)
#define unpack_fp_vec                                   CRYPTO_NAMESPACE(unpack_fp_vec)
#define unpack_fz_rsdp_g_vec                            CRYPTO_NAMESPACE(unpack_fz_rsdp_g_vec)
#define unpack_fz_vec                                   CRYPTO_NAMESPACE(unpack_fz_vec)

#define shake128_inc_init                               CRYPTO_NAMESPACE(shake128_inc_init)
#define shake128_inc_absorb                             CRYPTO_NAMESPACE(shake128_inc_absorb)
#define shake128_inc_finalize                           CRYPTO_NAMESPACE(shake128_inc_finalize)
#define shake128_inc_squeeze                            CRYPTO_NAMESPACE(shake128_inc_squeeze)
#define shake256_inc_init                               CRYPTO_NAMESPACE(shake256_inc_init)
#define shake256_inc_absorb                             CRYPTO_NAMESPACE(shake256_inc_absorb)
#define shake256_inc_finalize                           CRYPTO_NAMESPACE(shake256_inc_finalize)
#define shake256_inc_squeeze                            CRYPTO_NAMESPACE(shake256_inc_squeeze)
#define shake128_absorb                                 CRYPTO_NAMESPACE(shake128_absorb)
#define shake128_squeezeblocks                          CRYPTO_NAMESPACE(shake128_squeezeblocks)
#define shake128                                        CRYPTO_NAMESPACE(shake128)
#define shake128_ctx_clone                              CRYPTO_NAMESPACE(shake128_ctx_clone)
#define shake256_absorb                                 CRYPTO_NAMESPACE(shake256_absorb)
#define shake256_squeezeblocks                          CRYPTO_NAMESPACE(shake256_squeezeblocks)
#define shake256                                        CRYPTO_NAMESPACE(shake256)
#define shake256_ctx_clone                              CRYPTO_NAMESPACE(shake256_ctx_clone)
#define sha3_256                                        CRYPTO_NAMESPACE(sha3_256)
#define sha3_256_inc_init                               CRYPTO_NAMESPACE(sha3_256_inc_init)
#define sha3_256_inc_absorb                             CRYPTO_NAMESPACE(sha3_256_inc_absorb)
#define sha3_256_inc_finalize                           CRYPTO_NAMESPACE(sha3_256_inc_finalize)
#define sha3_384_inc_init                               CRYPTO_NAMESPACE(sha3_384_inc_init)
#define sha3_384_inc_absorb                             CRYPTO_NAMESPACE(sha3_384_inc_absorb)
#define sha3_384_inc_finalize                           CRYPTO_NAMESPACE(sha3_384_inc_finalize)
#define sha3_384                                        CRYPTO_NAMESPACE(sha3_384)
#define sha3_512                                        CRYPTO_NAMESPACE(sha3_512)
#define sha3_512_inc_init                               CRYPTO_NAMESPACE(sha3_512_inc_init)
#define sha3_512_inc_absorb                             CRYPTO_NAMESPACE(sha3_512_inc_absorb)
#define sha3_512_inc_finalize                           CRYPTO_NAMESPACE(sha3_512_inc_finalize)

#define KeccakF1600_StateExtractBytes                   CRYPTO_NAMESPACE(KeccakF1600_StateExtractBytes)
#define KeccakF1600_StateXORBytes                       CRYPTO_NAMESPACE(KeccakF1600_StateXORBytes)
#define KeccakF1600_StatePermute                        CRYPTO_NAMESPACE(KeccakF1600_StatePermute)

#define KeccakP1600times4_InitializeAll                 CRYPTO_NAMESPACE(KeccakP1600times4_InitializeAll)
#define KeccakP1600times4_AddBytes                      CRYPTO_NAMESPACE(KeccakP1600times4_AddBytes)
#define KeccakP1600times4_AddLanesAll                   CRYPTO_NAMESPACE(KeccakP1600times4_AddLanesAll)
#define KeccakP1600times4_OverwriteBytes                CRYPTO_NAMESPACE(KeccakP1600times4_OverwriteBytes)
#define KeccakP1600times4_OverwriteLanesAll             CRYPTO_NAMESPACE(KeccakP1600times4_OverwriteLanesAll)
#define KeccakP1600times4_OverwriteWithZeroes           CRYPTO_NAMESPACE(KeccakP1600times4_OverwriteWithZeroes)
#define KeccakP1600times4_ExtractBytes                  CRYPTO_NAMESPACE(KeccakP1600times4_ExtractBytes)
#define KeccakP1600times4_ExtractLanesAll               CRYPTO_NAMESPACE(KeccakP1600times4_ExtractLanesAll)
#define KeccakP1600times4_ExtractAndAddBytes            CRYPTO_NAMESPACE(KeccakP1600times4_ExtractAndAddBytes)
#define KeccakP1600times4_ExtractAndAddLanesAll         CRYPTO_NAMESPACE(KeccakP1600times4_ExtractAndAddLanesAll)
#define KeccakP1600times4_PermuteAll_24rounds           CRYPTO_NAMESPACE(KeccakP1600times4_PermuteAll_24rounds)
#define KeccakP1600times4_PermuteAll_12rounds           CRYPTO_NAMESPACE(KeccakP1600times4_PermuteAll_12rounds)
#define KeccakP1600times4_PermuteAll_6rounds            CRYPTO_NAMESPACE(KeccakP1600times4_PermuteAll_6rounds)
#define KeccakP1600times4_PermuteAll_4rounds            CRYPTO_NAMESPACE(KeccakP1600times4_PermuteAll_4rounds)
#define KeccakF1600times4_FastLoop_Absorb               CRYPTO_NAMESPACE(KeccakF1600times4_FastLoop_Absorb)
#define KeccakP1600times4_12rounds_FastLoop_Absorb      CRYPTO_NAMESPACE(KeccakP1600times4_12rounds_FastLoop_Absorb)
#define KeccakP1600times4_KravatteCompress              CRYPTO_NAMESPACE(KeccakP1600times4_KravatteCompress)
#define KeccakP1600times4_KravatteExpand                CRYPTO_NAMESPACE(KeccakP1600times4_KravatteExpand)

#define keccak_x4_init                                  CRYPTO_NAMESPACE(keccak_x4_init)
#define keccak_x4_absorb                                CRYPTO_NAMESPACE(keccak_x4_absorb)
#define keccak_x4_finalize                              CRYPTO_NAMESPACE(keccak_x4_finalize)
#define keccak_x4_squeeze                               CRYPTO_NAMESPACE(keccak_x4_squeeze)

#define pseed                                           CRYPTO_NAMESPACE(pseed)
#define psalt                                           CRYPTO_NAMESPACE(psalt)
#define ptree                                           CRYPTO_NAMESPACE(ptree)