#ifndef __PARAMETERS_H__
#define __PARAMETERS_H__

#define MQOM2_PARAM_SECURITY 256
#define MQOM2_PARAM_BASE_FIELD 8
#define MQOM2_PARAM_TRADEOFF 1
#define MQOM2_PARAM_NBROUNDS 5

#define FIELDS_AVX512

#define NO_MISALIGNED_ACCESSES
#define USE_PRG_CACHE
#define USE_PIOP_CACHE
#define USE_XOF_X4
#define USE_ENC_X8

#define MQOM2_FOR_SUPERCOP

#endif /* __PARAMETERS_H__ */
